spring.application.name=resource-system


# Database Configuration (PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/${POSTGRES_DB:mydatabase}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:myuser}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:secret}}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Messaging Configuration (RabbitMQ)
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:${RABBITMQ_USER:myuser}}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:${RABBITMQ_PASSWORD:secret}}
