CREATE TYPE "condition_status" AS ENUM (
  'good',
  'bad',
  'normal',
  'other'
);

CREATE TYPE "donation_status" AS ENUM (
  'registered',
  'pending_approval',
  'completed',
  'awaiting_shipment',
  'other'
);

CREATE TYPE "necessity_status" AS ENUM (
  'registered',
  'pending_approval',
  'completed',
  'awaiting_shipment',
  'other'
);

CREATE TYPE "match_status" AS ENUM (
  'registered',
  'pending_approval',
  'completed',
  'awaiting_shipment',
  'other'
);

CREATE TYPE "necessity_level" AS ENUM (
  'high',
  'medium',
  'low'
);

CREATE TYPE "item_category" AS ENUM (
  'food',
  'clothing',
  'household',
  'toy',
  'other'
);

CREATE TABLE "state" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

CREATE TABLE "city" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "state_id" integer NOT NULL,
  "name" varchar NOT NULL
);

CREATE TABLE "address_donation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "city_id" integer NOT NULL,
  "cep" char(8) NOT NULL CHECK (cep ~ '^[0-9]{8}$'),
  "address" varchar NOT NULL,
  "complement" varchar,
  "number" varchar NOT NULL,
  "district" varchar NOT NULL
);

CREATE TABLE "user" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar NOT NULL,
  "cpf" char(11) UNIQUE NOT NULL CHECK (cep ~ '^[0-9]{8}$'),
  "email" citext UNIQUE NOT NULL,
  "city_id" integer NOT NULL
);

CREATE TABLE "institution" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar NOT NULL,
  "email" citext UNIQUE NOT NULL,
  "representative_full_name" varchar NOT NULL,
  "representative_cpf" char(11) UNIQUE NOT NULL CHECK (representative_cpf ~ '^[0-9]{11}$'),
  "address_donation_id" integer UNIQUE NOT NULL,
  "business_hours_id" integer UNIQUE NOT NULL
);

CREATE TABLE "open_days" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "monday" boolean NOT NULL DEFAULT false,
  "tuesday" boolean NOT NULL DEFAULT false,
  "wednesday" boolean NOT NULL DEFAULT false,
  "thursday" boolean NOT NULL DEFAULT false,
  "friday" boolean NOT NULL DEFAULT false,
  "saturday" boolean NOT NULL DEFAULT false,
  "sunday" boolean NOT NULL DEFAULT false,

  CONSTRAINT open_days_combination_unique 
    UNIQUE (monday, tuesday, wednesday, thursday, friday, saturday, sunday),
  CONSTRAINT open_days_at_least_one_day 
    CHECK (monday OR tuesday OR wednesday OR thursday OR friday OR saturday OR sunday)
);

CREATE TABLE "business_hours" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "responsible_name" varchar NOT NULL,
  "opening_hour" time NOT NULL,
  "closing_hour" time NOT NULL,
  "open_days_id" integer NOT NULL,
  
  CONSTRAINT business_hours_period_valid CHECK (closing_hour > opening_hour)
);

CREATE TABLE "item_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category" item_category NOT NULL,
  "name" varchar NOT NULL
);

CREATE TABLE "item" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "item_type_id" integer NOT NULL,
  "title" varchar NOT NULL,
  "condition" condition_status NOT NULL
);

CREATE TABLE "package" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "item_id" integer NOT NULL,
  "number_items" integer NOT NULL CHECK (number_items > 0),
  "description_items" varchar
);

CREATE TABLE "donation" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "package_id" integer UNIQUE NOT NULL,
  "status" donation_status NOT NULL DEFAULT 'registered',
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "necessity" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "institution_id" integer NOT NULL,
  "item_type_id" integer NOT NULL,
  "number_items" integer NOT NULL CHECK (number_items > 0),
  "priority_level" necessity_level NOT NULL,
  "status" necessity_status NOT NULL DEFAULT 'registered',
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "match" (
  "donation_id" integer NOT NULL,
  "necessity_id" integer NOT NULL,
  "status" match_status NOT NULL DEFAULT 'registered',
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  PRIMARY KEY ("donation_id", "necessity_id")
);

CREATE UNIQUE INDEX ON "city" ("state_id", "name");

CREATE INDEX ON "address_donation" ("city_id");

CREATE INDEX ON "user" ("city_id");

CREATE UNIQUE INDEX ON "open_days" ("monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday");

CREATE INDEX ON "business_hours" ("open_days_id");

CREATE UNIQUE INDEX ON "item_type" ("category", "name");

CREATE INDEX ON "item" ("item_type_id");

CREATE INDEX ON "package" ("item_id");

CREATE INDEX ON "donation" ("user_id");

CREATE INDEX ON "necessity" ("institution_id");

CREATE INDEX ON "necessity" ("item_type_id");

CREATE INDEX ON "match" ("necessity_id");

COMMENT ON COLUMN "address_donation"."cep" IS 'somente dígitos';

COMMENT ON COLUMN "address_donation"."number" IS 'aceita "S/N", "12A"';

COMMENT ON COLUMN "user"."cpf" IS 'somente dígitos';

COMMENT ON COLUMN "institution"."representative_cpf" IS 'somente dígitos';

COMMENT ON COLUMN "institution"."address_donation_id" IS 'um único endereço por instituição';

COMMENT ON COLUMN "package"."description_items" IS 'descrição geral';

ALTER TABLE "city" ADD FOREIGN KEY ("state_id") REFERENCES "state" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "address_donation" ADD FOREIGN KEY ("city_id") REFERENCES "city" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user" ADD FOREIGN KEY ("city_id") REFERENCES "city" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "institution" ADD FOREIGN KEY ("address_donation_id") REFERENCES "address_donation" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "institution" ADD FOREIGN KEY ("business_hours_id") REFERENCES "business_hours" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "business_hours" ADD FOREIGN KEY ("open_days_id") REFERENCES "open_days" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "item" ADD FOREIGN KEY ("item_type_id") REFERENCES "item_type" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "package" ADD FOREIGN KEY ("item_id") REFERENCES "item" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "donation" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "donation" ADD FOREIGN KEY ("package_id") REFERENCES "package" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "necessity" ADD FOREIGN KEY ("institution_id") REFERENCES "institution" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "necessity" ADD FOREIGN KEY ("item_type_id") REFERENCES "item_type" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "match" ADD FOREIGN KEY ("donation_id") REFERENCES "donation" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "match" ADD FOREIGN KEY ("necessity_id") REFERENCES "necessity" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
