CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name varchar NOT NULL,
  cpf char(11) UNIQUE NOT NULL CHECK (cpf ~ '^[0-9]{11}$'),
  email citext UNIQUE NOT NULL,
  city_id integer NOT NULL REFERENCES cities (id) ON DELETE RESTRICT
);

CREATE INDEX ON users (city_id);
