CREATE TABLE necessities (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institution_id integer NOT NULL REFERENCES institutions (id) ON DELETE RESTRICT,
  item_type_id integer NOT NULL REFERENCES item_types (id) ON DELETE RESTRICT,
  number_items integer NOT NULL CHECK (number_items > 0),
  priority_level necessity_level NOT NULL,
  status record_status NOT NULL DEFAULT 'registered',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ON necessities (institution_id);
CREATE INDEX ON necessities (item_type_id);
