CREATE TABLE donations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
  package_id integer UNIQUE NOT NULL REFERENCES packages (id) ON DELETE RESTRICT,
  status record_status NOT NULL DEFAULT 'registered',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ON donations (user_id);
