CREATE TABLE item_types (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category item_category NOT NULL,
  name varchar NOT NULL,

  CONSTRAINT item_types_category_name_unique UNIQUE (category, name)
);
