CREATE TABLE items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_type_id integer NOT NULL REFERENCES item_types (id) ON DELETE RESTRICT,
  title varchar NOT NULL,
  condition condition_status NOT NULL
);

CREATE INDEX ON items (item_type_id);
