CREATE TABLE business_hours (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  responsible_name varchar NOT NULL,
  opening_hour time NOT NULL,
  closing_hour time NOT NULL,
  open_days_id integer NOT NULL REFERENCES open_days (id) ON DELETE RESTRICT,

  CONSTRAINT business_hours_period_valid CHECK (closing_hour > opening_hour)
);

CREATE INDEX ON business_hours (open_days_id);
