CREATE TABLE cities (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  state_id integer NOT NULL,
  name varchar(150) NOT NULL,
  latitude numeric(9, 6),
  longitude numeric(9, 6),

  CONSTRAINT pk_cities PRIMARY KEY (id),
  CONSTRAINT fk_cities_state FOREIGN KEY (state_id) REFERENCES states (id) ON DELETE RESTRICT,
  CONSTRAINT uq_cities_state_name UNIQUE (state_id, name),
  CONSTRAINT ck_cities_latitude CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
  CONSTRAINT ck_cities_longitude CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
  CONSTRAINT ck_cities_coordinates CHECK ((latitude IS NULL) = (longitude IS NULL))
);

CREATE INDEX idx_cities_state_id ON cities (state_id);
