CREATE TABLE cities (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  state_id integer NOT NULL,
  name varchar NOT NULL,

  CONSTRAINT pk_cities PRIMARY KEY (id),
  CONSTRAINT fk_cities_state FOREIGN KEY (state_id) REFERENCES states (id) ON DELETE RESTRICT,
  CONSTRAINT unq_cities_state_id_name UNIQUE (state_id, name)
);
