CREATE TABLE users (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  full_name varchar(200) NOT NULL,
  cpf char(11),
  email varchar(320) NOT NULL,
  password_hash varchar(255),
  oauth_provider varchar(50),
  oauth_subject varchar(255),
  role account_role NOT NULL DEFAULT 'donor',
  status account_status NOT NULL DEFAULT 'active',
  city_id integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  last_login_at timestamptz,

  CONSTRAINT pk_users PRIMARY KEY (id),
  CONSTRAINT fk_users_city FOREIGN KEY (city_id) REFERENCES cities (id) ON DELETE RESTRICT,
  CONSTRAINT uq_users_cpf UNIQUE (cpf),
  CONSTRAINT uq_users_oauth_identity UNIQUE (oauth_provider, oauth_subject),
  CONSTRAINT ck_users_cpf_format CHECK (cpf IS NULL OR cpf ~ '^[0-9]{11}$'),
  CONSTRAINT ck_users_authentication CHECK (
    password_hash IS NOT NULL OR (oauth_provider IS NOT NULL AND oauth_subject IS NOT NULL)
  ),
  CONSTRAINT ck_users_oauth_pair CHECK (
    (oauth_provider IS NULL AND oauth_subject IS NULL)
    OR (oauth_provider IS NOT NULL AND oauth_subject IS NOT NULL)
  )
);

CREATE INDEX idx_users_city_id ON users (city_id);
CREATE INDEX idx_users_role_status ON users (role, status);
CREATE UNIQUE INDEX uq_users_email_ci ON users (lower(email));
