CREATE TABLE cities (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  state_id integer NOT NULL REFERENCES states (id) ON DELETE RESTRICT,
  name varchar NOT NULL,

  CONSTRAINT cities_state_id_name_unique UNIQUE (state_id, name)
);
