CREATE TABLE institutions (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  cnpj char(14) NOT NULL,
  legal_name varchar(200) NOT NULL,
  email varchar(320) NOT NULL,
  password_hash varchar(255) NOT NULL,
  representative_full_name varchar(200) NOT NULL,
  representative_cpf char(11) NOT NULL,
  description text,
  sector institution_sector NOT NULL DEFAULT 'other',
  logo_url varchar(500),
  cover_image_url varchar(500),
  status institution_status NOT NULL DEFAULT 'pending_approval',
  rejection_reason text,
  reviewed_at timestamptz,
  reviewed_by_user_id integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT pk_institutions PRIMARY KEY (id),
  CONSTRAINT fk_institutions_reviewer FOREIGN KEY (reviewed_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
  CONSTRAINT uq_institutions_cnpj UNIQUE (cnpj),
  CONSTRAINT uq_institutions_representative_cpf UNIQUE (representative_cpf),
  CONSTRAINT ck_institutions_cnpj_format CHECK (cnpj ~ '^[0-9]{14}$'),
  CONSTRAINT ck_institutions_representative_cpf_format CHECK (representative_cpf ~ '^[0-9]{11}$'),
  CONSTRAINT ck_institutions_rejection_reason CHECK (
    status <> 'rejected' OR rejection_reason IS NOT NULL
  )
);

CREATE INDEX idx_institutions_status ON institutions (status);
CREATE INDEX idx_institutions_sector ON institutions (sector);
CREATE UNIQUE INDEX uq_institutions_email_ci ON institutions (lower(email));
