CREATE TABLE address_donations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city_id integer NOT NULL REFERENCES cities (id) ON DELETE RESTRICT,
  cep char(8) NOT NULL CHECK (cep ~ '^[0-9]{8}$'),
  address varchar NOT NULL,
  complement varchar,
  number varchar NOT NULL,
  district varchar NOT NULL
);

CREATE INDEX ON address_donations (city_id);
