CREATE TABLE address_donations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  city_id integer NOT NULL,
  cep char(8) NOT NULL,
  address varchar NOT NULL,
  complement varchar,
  number varchar NOT NULL,
  district varchar NOT NULL,

  CONSTRAINT pk_address_donations PRIMARY KEY (id),
  CONSTRAINT fk_address_donations_city FOREIGN KEY (city_id) REFERENCES cities (id) ON DELETE RESTRICT,
  CONSTRAINT chk_address_donations_cep CHECK (cep ~ '^[0-9]{8}$')
);

CREATE INDEX ON address_donations (city_id);
