CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  full_name varchar NOT NULL,
  cpf char(11) NOT NULL,
  email citext NOT NULL,
  city_id integer NOT NULL,

  CONSTRAINT pk_users PRIMARY KEY (id),
  CONSTRAINT fk_users_city FOREIGN KEY (city_id) REFERENCES cities (id) ON DELETE RESTRICT,
  CONSTRAINT unq_users_cpf UNIQUE (cpf),
  CONSTRAINT unq_users_email UNIQUE (email),
  CONSTRAINT chk_users_cpf CHECK (cpf ~ '^[0-9]{11}$')
);

CREATE INDEX ON users (city_id);
