CREATE TABLE institution_addresses (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  institution_id integer NOT NULL,
  city_id integer NOT NULL,
  cep char(8) NOT NULL,
  street varchar(200) NOT NULL,
  number varchar(30) NOT NULL,
  complement varchar(150),
  district varchar(120) NOT NULL,

  CONSTRAINT pk_institution_addresses PRIMARY KEY (id),
  CONSTRAINT fk_institution_addresses_institution FOREIGN KEY (institution_id) REFERENCES institutions (id) ON DELETE CASCADE,
  CONSTRAINT fk_institution_addresses_city FOREIGN KEY (city_id) REFERENCES cities (id) ON DELETE RESTRICT,
  CONSTRAINT uq_institution_addresses_institution UNIQUE (institution_id),
  CONSTRAINT ck_institution_addresses_cep_format CHECK (cep ~ '^[0-9]{8}$')
);

CREATE INDEX idx_institution_addresses_city_id ON institution_addresses (city_id);
