CREATE TABLE institution_documents (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  institution_id integer NOT NULL,
  document_type document_type NOT NULL,
  original_file_name varchar(255) NOT NULL,
  storage_key varchar(500) NOT NULL,
  content_type varchar(100) NOT NULL,
  file_size_bytes bigint NOT NULL,
  status document_status NOT NULL DEFAULT 'pending',
  rejection_reason text,
  uploaded_at timestamptz NOT NULL DEFAULT now(),
  reviewed_at timestamptz,
  reviewed_by_user_id integer,

  CONSTRAINT pk_institution_documents PRIMARY KEY (id),
  CONSTRAINT fk_institution_documents_institution FOREIGN KEY (institution_id) REFERENCES institutions (id) ON DELETE CASCADE,
  CONSTRAINT fk_institution_documents_reviewer FOREIGN KEY (reviewed_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
  CONSTRAINT uq_institution_documents_type UNIQUE (institution_id, document_type),
  CONSTRAINT uq_institution_documents_storage_key UNIQUE (storage_key),
  CONSTRAINT ck_institution_documents_file_size CHECK (file_size_bytes > 0),
  CONSTRAINT ck_institution_documents_rejection_reason CHECK (
    status <> 'rejected' OR rejection_reason IS NOT NULL
  )
);

CREATE INDEX idx_institution_documents_status ON institution_documents (status);
