CREATE TABLE open_days (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  monday boolean NOT NULL DEFAULT false,
  tuesday boolean NOT NULL DEFAULT false,
  wednesday boolean NOT NULL DEFAULT false,
  thursday boolean NOT NULL DEFAULT false,
  friday boolean NOT NULL DEFAULT false,
  saturday boolean NOT NULL DEFAULT false,
  sunday boolean NOT NULL DEFAULT false,

  CONSTRAINT pk_open_days PRIMARY KEY (id),
  CONSTRAINT unq_open_days_combination
    UNIQUE (monday, tuesday, wednesday, thursday, friday, saturday, sunday),
  CONSTRAINT chk_open_days_at_least_one_day
    CHECK (monday OR tuesday OR wednesday OR thursday OR friday OR saturday OR sunday)
);
