CREATE TABLE business_hours (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  responsible_name varchar NOT NULL,
  opening_hour time NOT NULL,
  closing_hour time NOT NULL,
  open_days_id integer NOT NULL,

  CONSTRAINT pk_business_hours PRIMARY KEY (id),
  CONSTRAINT fk_business_hours_open_days FOREIGN KEY (open_days_id) REFERENCES open_days (id) ON DELETE RESTRICT,
  CONSTRAINT chk_business_hours_period_valid CHECK (closing_hour > opening_hour)
);

CREATE INDEX ON business_hours (open_days_id);
