CREATE TABLE business_hours (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  institution_id integer NOT NULL,
  open_days_id integer NOT NULL,
  responsible_name varchar(200) NOT NULL,
  opening_hour time NOT NULL,
  closing_hour time NOT NULL,

  CONSTRAINT pk_business_hours PRIMARY KEY (id),
  CONSTRAINT fk_business_hours_institution FOREIGN KEY (institution_id) REFERENCES institutions (id) ON DELETE CASCADE,
  CONSTRAINT fk_business_hours_open_days FOREIGN KEY (open_days_id) REFERENCES open_days (id) ON DELETE RESTRICT,
  CONSTRAINT ck_business_hours_period_valid CHECK (closing_hour > opening_hour)
);

CREATE INDEX idx_business_hours_institution_id ON business_hours (institution_id);
