CREATE TABLE institutions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name varchar NOT NULL,
  email citext UNIQUE NOT NULL,
  representative_full_name varchar NOT NULL,
  representative_cpf char(11) UNIQUE NOT NULL CHECK (representative_cpf ~ '^[0-9]{11}$'),
  address_donation_id integer UNIQUE NOT NULL REFERENCES address_donations (id) ON DELETE RESTRICT,
  business_hours_id integer UNIQUE NOT NULL REFERENCES business_hours (id) ON DELETE RESTRICT
);
