CREATE TABLE institutions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  full_name varchar NOT NULL,
  email citext NOT NULL,
  representative_full_name varchar NOT NULL,
  representative_cpf char(11) NOT NULL,
  address_donation_id integer NOT NULL,
  business_hours_id integer NOT NULL,

  CONSTRAINT pk_institutions PRIMARY KEY (id),
  CONSTRAINT fk_institutions_address_donation FOREIGN KEY (address_donation_id) REFERENCES address_donations (id) ON DELETE RESTRICT,
  CONSTRAINT fk_institutions_business_hours FOREIGN KEY (business_hours_id) REFERENCES business_hours (id) ON DELETE RESTRICT,
  CONSTRAINT unq_institutions_email UNIQUE (email),
  CONSTRAINT unq_institutions_representative_cpf UNIQUE (representative_cpf),
  CONSTRAINT unq_institutions_address_donation_id UNIQUE (address_donation_id),
  CONSTRAINT unq_institutions_business_hours_id UNIQUE (business_hours_id),
  CONSTRAINT chk_institutions_representative_cpf CHECK (representative_cpf ~ '^[0-9]{11}$')
);
