CREATE TABLE item_types (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  category item_category NOT NULL,
  name varchar(150) NOT NULL,

  CONSTRAINT pk_item_types PRIMARY KEY (id),
  CONSTRAINT uq_item_types_category_name UNIQUE (category, name)
);
