CREATE TABLE item_types (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  category item_category NOT NULL,
  name varchar NOT NULL,

  CONSTRAINT pk_item_types PRIMARY KEY (id),
  CONSTRAINT unq_item_types_category_name UNIQUE (category, name)
);
