CREATE TABLE items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  item_type_id integer NOT NULL,
  title varchar NOT NULL,
  condition condition_status NOT NULL,

  CONSTRAINT pk_items PRIMARY KEY (id),
  CONSTRAINT fk_items_item_type FOREIGN KEY (item_type_id) REFERENCES item_types (id) ON DELETE RESTRICT
);

CREATE INDEX ON items (item_type_id);
