CREATE TABLE items (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  item_type_id integer NOT NULL,
  title varchar(200) NOT NULL,
  condition item_condition NOT NULL,
  description text,
  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT pk_items PRIMARY KEY (id),
  CONSTRAINT fk_items_item_type FOREIGN KEY (item_type_id) REFERENCES item_types (id) ON DELETE RESTRICT
);

CREATE INDEX idx_items_item_type_id ON items (item_type_id);
