CREATE TABLE packages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  item_id integer NOT NULL,
  number_items integer NOT NULL,
  description_items varchar,

  CONSTRAINT pk_packages PRIMARY KEY (id),
  CONSTRAINT fk_packages_item FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE RESTRICT,
  CONSTRAINT chk_packages_number_items CHECK (number_items > 0)
);

CREATE INDEX ON packages (item_id);
