CREATE TABLE packages (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  item_id integer NOT NULL,
  quantity integer NOT NULL,
  description text,

  CONSTRAINT pk_packages PRIMARY KEY (id),
  CONSTRAINT fk_packages_item FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE RESTRICT,
  CONSTRAINT ck_packages_quantity_positive CHECK (quantity > 0)
);

CREATE INDEX idx_packages_item_id ON packages (item_id);
