CREATE TABLE packages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id integer NOT NULL REFERENCES items (id) ON DELETE RESTRICT,
  number_items integer NOT NULL CHECK (number_items > 0),
  description_items varchar
);

CREATE INDEX ON packages (item_id);
