CREATE TABLE donations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  user_id integer NOT NULL,
  package_id integer NOT NULL,
  status record_status NOT NULL DEFAULT 'registered',
  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT pk_donations PRIMARY KEY (id),
  CONSTRAINT fk_donations_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
  CONSTRAINT fk_donations_package FOREIGN KEY (package_id) REFERENCES packages (id) ON DELETE RESTRICT,
  CONSTRAINT unq_donations_package_id UNIQUE (package_id)
);

CREATE INDEX ON donations (user_id);
