CREATE TABLE donations (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  donor_user_id integer NOT NULL,
  package_id integer NOT NULL,
  status donation_status NOT NULL DEFAULT 'registered',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT pk_donations PRIMARY KEY (id),
  CONSTRAINT fk_donations_donor FOREIGN KEY (donor_user_id) REFERENCES users (id) ON DELETE RESTRICT,
  CONSTRAINT fk_donations_package FOREIGN KEY (package_id) REFERENCES packages (id) ON DELETE RESTRICT,
  CONSTRAINT uq_donations_package UNIQUE (package_id)
);

CREATE INDEX idx_donations_donor_user_id ON donations (donor_user_id);
CREATE INDEX idx_donations_status ON donations (status);
