CREATE TABLE necessities (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  institution_id integer NOT NULL,
  item_type_id integer NOT NULL,
  number_items integer NOT NULL,
  priority_level necessity_level NOT NULL,
  status record_status NOT NULL DEFAULT 'registered',
  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT pk_necessities PRIMARY KEY (id),
  CONSTRAINT fk_necessities_institution FOREIGN KEY (institution_id) REFERENCES institutions (id) ON DELETE RESTRICT,
  CONSTRAINT fk_necessities_item_type FOREIGN KEY (item_type_id) REFERENCES item_types (id) ON DELETE RESTRICT,
  CONSTRAINT chk_necessities_number_items CHECK (number_items > 0)
);

CREATE INDEX ON necessities (institution_id);
CREATE INDEX ON necessities (item_type_id);
