CREATE TABLE necessities (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  institution_id integer NOT NULL,
  item_type_id integer NOT NULL,
  quantity_requested integer NOT NULL,
  description text,
  priority necessity_priority NOT NULL DEFAULT 'medium',
  status necessity_status NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT pk_necessities PRIMARY KEY (id),
  CONSTRAINT fk_necessities_institution FOREIGN KEY (institution_id) REFERENCES institutions (id) ON DELETE RESTRICT,
  CONSTRAINT fk_necessities_item_type FOREIGN KEY (item_type_id) REFERENCES item_types (id) ON DELETE RESTRICT,
  CONSTRAINT ck_necessities_quantity_positive CHECK (quantity_requested > 0)
);

CREATE INDEX idx_necessities_institution_id ON necessities (institution_id);
CREATE INDEX idx_necessities_item_type_id ON necessities (item_type_id);
CREATE INDEX idx_necessities_status_priority ON necessities (status, priority);
