CREATE TABLE matches (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  donation_id integer NOT NULL,
  necessity_id integer NOT NULL,
  allocated_quantity integer NOT NULL,
  status match_status NOT NULL DEFAULT 'proposed',
  acceptance_deadline timestamptz NOT NULL DEFAULT (now() + interval '7 days'),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT pk_matches PRIMARY KEY (id),
  CONSTRAINT fk_matches_donation FOREIGN KEY (donation_id) REFERENCES donations (id) ON DELETE CASCADE,
  CONSTRAINT fk_matches_necessity FOREIGN KEY (necessity_id) REFERENCES necessities (id) ON DELETE CASCADE,
  CONSTRAINT uq_matches_donation_necessity UNIQUE (donation_id, necessity_id),
  CONSTRAINT ck_matches_allocated_quantity_positive CHECK (allocated_quantity > 0)
);

CREATE INDEX idx_matches_necessity_id ON matches (necessity_id);
CREATE INDEX idx_matches_status ON matches (status);
