CREATE TABLE deliveries (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  match_id integer NOT NULL,
  method delivery_method NOT NULL,
  status delivery_status NOT NULL DEFAULT 'pending',
  pickup_address text,
  delivery_address text,
  carrier_name varchar(150),
  tracking_code varchar(150),
  scheduled_at timestamptz,
  shipped_at timestamptz,
  delivered_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT pk_deliveries PRIMARY KEY (id),
  CONSTRAINT fk_deliveries_match FOREIGN KEY (match_id) REFERENCES matches (id) ON DELETE CASCADE,
  CONSTRAINT uq_deliveries_match UNIQUE (match_id),
  CONSTRAINT ck_deliveries_tracking_code CHECK (
    method <> 'carrier' OR tracking_code IS NOT NULL
  ),
  CONSTRAINT ck_deliveries_delivered_at CHECK (
    status <> 'delivered' OR delivered_at IS NOT NULL
  )
);

CREATE INDEX idx_deliveries_status ON deliveries (status);
