CREATE TABLE donation_status_history (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  donation_id integer NOT NULL,
  previous_status donation_status,
  new_status donation_status NOT NULL,
  changed_by_user_id integer,
  notes text,
  changed_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT pk_donation_status_history PRIMARY KEY (id),
  CONSTRAINT fk_donation_status_history_donation FOREIGN KEY (donation_id) REFERENCES donations (id) ON DELETE CASCADE,
  CONSTRAINT fk_donation_status_history_user FOREIGN KEY (changed_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
  CONSTRAINT ck_donation_status_history_transition CHECK (
    previous_status IS NULL OR previous_status <> new_status
  )
);

CREATE INDEX idx_donation_status_history_donation_id ON donation_status_history (donation_id, changed_at);
