CREATE TABLE match_status_history (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  match_id integer NOT NULL,
  previous_status match_status,
  new_status match_status NOT NULL,
  changed_by_user_id integer,
  notes text,
  changed_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT pk_match_status_history PRIMARY KEY (id),
  CONSTRAINT fk_match_status_history_match FOREIGN KEY (match_id) REFERENCES matches (id) ON DELETE CASCADE,
  CONSTRAINT fk_match_status_history_user FOREIGN KEY (changed_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
  CONSTRAINT ck_match_status_history_transition CHECK (
    previous_status IS NULL OR previous_status <> new_status
  )
);

CREATE INDEX idx_match_status_history_match_id ON match_status_history (match_id, changed_at);
